# Generated by Django 4.0.5 on 2022-07-12 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ad_brand_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lebels',
            new_name='labels',
        ),
    ]
