# Generated by Django 4.0.5 on 2022-08-03 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_oderplace_orderplace_oderitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplace',
            old_name='grand_total',
            new_name='grand_totalss',
        ),
    ]
