# Generated by Django 4.0.5 on 2022-08-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_orderplace_grand_totalss'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderitems',
            name='image',
            field=models.ImageField(default=0, upload_to='media'),
        ),
        migrations.AddField(
            model_name='oderitems',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='oderitems',
            name='product',
            field=models.CharField(max_length=200),
        ),
    ]
