# Generated by Django 4.0.5 on 2022-08-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_oderitems_image_remove_oderitems_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderplace',
            name='grand_totalss',
            field=models.IntegerField(),
        ),
    ]
